spring:
  profiles:
    active: native
  application:
    name: config-server
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
