spring:
  output:
    ansi:
      enabled: always
  application:
    name: human-resource
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5332/hr
    username: sacco
    password: sacco
    driver-class-name: org.postgresql.Driver


